In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import NMF

In [2]:
df_1 = pd.read_csv('wikipedia-vocabulary-utf8.txt')

In [12]:
df_1

             aaron
0          abandon
1        abandoned
2       abandoning
3      abandonment
4            abbas
...            ...
13119     zimbabwe
13120         zinc
13121         zone
13122        zones
13123          zoo

[13124 rows x 1 columns]

In [3]:
df_2 = pd.read_csv('wikipedia-vectors.csv')

In [4]:
df_2_t= df_2.T

In [5]:
df_2_t

,0,1,2,3,4,5,6,7,8,9,...,13115,13116,13117,13118,13119,13120,13121,13122,13123,13124
Unnamed: 0,0.000000,1.00000,2.000000,3.000000,4.0,5.0,6.0,7.000000,8.0,9.000000,...,13115.000000,13116.0,13117.000000,13118.0,13119.0,13120.0,13121.0,13122.000000,13123.000000,13124.0
HTTP 404,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
Alexa Internet,0.000000,0.00000,0.029607,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
Internet Explorer,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.003772,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.011594,0.000000,0.0
HTTP cookie,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Black Sabbath,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.003638,...,0.006873,0.0,0.005783,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
Skrillex,0.049502,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
Red Hot Chili Peppers,0.000000,0.00000,0.000000,0.005646,0.0,0.0,0.0,0.004690,0.0,0.000000,...,0.007140,0.0,0.012016,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
Sepsis,0.000000,0.00611,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.005476,0.0
Adam Levine,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0

In [6]:
model = NMF(n_components=6)

In [7]:
model.fit(df_2_t)

NMF(n_components=6)

In [8]:
nmf_features = model.transform(df_2_t)

In [9]:
print(nmf_features.round(2))

[[9.3171e+02 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 1.0000e-02 1.0000e-02 1.4000e-01]
 [0.0000e+00 1.0000e-02 1.0000e-02 1.0000e-02 4.0000e-02 1.7000e-01]
 [0.0000e+00 1.0000e-02 1.0000e-02 0.0000e+00 2.0000e-02 1.3000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 1.0000e-02 1.0000e-02 1.2000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 2.0000e-02 1.4000e-01]
 [0.0000e+00 2.0000e-02 2.0000e-02 2.0000e-02 6.0000e-02 1.0000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 3.0000e-02 0.0000e+00 1.2000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 2.0000e-02 1.4000e-01]
 [0.0000e+00 2.0000e-02 2.0000e-02 1.0000e-02 5.0000e-02 1.7000e-01]
 [0.0000e+00 1.0000e-02 4.0000e-02 4.0000e-02 9.0000e-02 1.2000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 5.3000e-01 0.0000e+00 2.0000e-02]
 [0.0000e+00 0.0000e+00 0.0000e+00 3.6000e-01 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.0000e-02 0.0000e+00 3.1000e-01 5.0000e-02 0.0000e+00]
 [0.0000e+00 1.0000e-02 1.0000e-02 3.4000e-01 1.0000e-02 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 4.3000e-01 0.0000e+00 3.0000e-02]
 [0.0000e+00 0.0000e+00 0.0000e+00 4.8000e-01 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.0000e-02 2.0000e-02 3.8000e-01 3.0000e-02 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 4.8000e-01 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.0000e-02 5.5000e-01 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 4.7000e-01 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.0000e-02 2.0000e-02 5.1000e-01 5.0000e-02]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 5.1000e-01 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.0000e-02 0.0000e+00 4.2000e-01 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 4.4000e-01 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 5.0000e-01 0.0000e+00]
 [0.0000e+00 1.1000e-01 9.0000e-02 1.0000e-02 3.8000e-01 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 5.7000e-01 0.0000e+00]
 [0.0000e+00 2.0000e-02 2.0000e-02 0.0000e+00 4.7000e-01 0.0000e+00]
 [0.0000e+00 1.0000e-02 0.0000e+00 0.0000e+00 5.8000e-01 0.0000e+00]
 [0.0000e+00 1.0000e-02 1.0000e-02 0.0000e+00 5.3000e-01 1.0000e-02]
 [0.0000e+00 0.0000e+00 4.1000e-01 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 6.1000e-01 0.0000e+00 1.0000e-02 0.0000e+00]
 [0.0000e+00 1.0000e-02 2.7000e-01 0.0000e+00 2.0000e-02 0.0000e+00]
 [0.0000e+00 0.0000e+00 6.5000e-01 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 6.1000e-01 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 3.4000e-01 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.0000e-02 3.2000e-01 1.0000e-02 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.0000e-02 2.1000e-01 1.0000e-02 4.0000e-02 1.0000e-02]
 [0.0000e+00 1.0000e-02 4.7000e-01 0.0000e+00 2.0000e-02 0.0000e+00]
 [0.0000e+00 0.0000e+00 6.5000e-01 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 4.7000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 4.8000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 3.8000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 5.3000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 1.0000e-02 0.0000e+00 4.2000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 5.0000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 3.7000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 3.0000e-02 0.0000e+00 2.2000e-01]
 [0.0000e+00 1.0000e-02 0.0000e+00 1.0000e-02 0.0000e+00 3.3000e-01]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 4.1000e-01]
 [0.0000e+00 3.3000e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 3.9000e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 4.3000e-01 3.0000e-02 1.0000e-02 2.0000e-02 1.0000e-02]
 [0.0000e+00 4.0000e-01 0.0000e+00 0.0000e+00 3.0000e-02 0.0000e+00]
 [0.0000e+00 4.7000e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 4.9000e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 3.0000e-01 1.0000e-02 0.0000e+00 5.0000e-02 0.0000e+00]
 [0.0000e+00 4.7000e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 3.1000e-01 1.0000e-02 1.0000e-02 0.0000e+00 1.7000e-01]
 [0.0000e+00 4.0000e-01 1.0000e-02 0.0000e+00 9.0000e-02 1.0000e-02]]

In [20]:
titles = df_2_t.index

In [21]:
df = pd.DataFrame(data=df_2_t, index = titles)

In [22]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,13115,13116,13117,13118,13119,13120,13121,13122,13123,13124
Unnamed: 0,0.0,1.0,2.000000,3.0,4.0,5.0,6.0,7.000000,8.0,9.0,...,13115.0,13116.0,13117.0,13118.0,13119.0,13120.0,13121.0,13122.000000,13123.0,13124.0
HTTP 404,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
Alexa Internet,0.0,0.0,0.029607,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
Internet Explorer,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.003772,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.011594,0.0,0.0
HTTP cookie,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [23]:
df.loc['Anne Hathaway']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
13120    0.0
13121    0.0
13122    0.0
13123    0.0
13124    0.0
Name: Anne Hathaway, Length: 13125, dtype: float64

In [24]:
df.loc['Denzel Washington']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
13120    0.0
13121    0.0
13122    0.0
13123    0.0
13124    0.0
Name: Denzel Washington, Length: 13125, dtype: float64